
CURRENCY_UAH = 'UAH'
CURRENCY_USD = 'USD'
CURRENCY_RUB = 'RUB'

CURRENCIES = (
    (CURRENCY_UAH, CURRENCY_UAH),
    (CURRENCY_USD, CURRENCY_USD),
    (CURRENCY_RUB, CURRENCY_RUB),
)


LANGUAGE_EN = 'en'
LANGUAGE_RU = 'ru'

LANGUAGES = (
    (LANGUAGE_EN, LANGUAGE_EN),
    (LANGUAGE_RU, LANGUAGE_RU)
)
